
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action HomesForSaleAction;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action CloseAction;

	private global::Gtk.Action NewAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action SaveAsAction;

	private global::Gtk.Action XmlAction;

	private global::Gtk.Action ImportFromXMLFileAction;

	private global::Gtk.Action ExportToXMLFileAction;

	private global::Gtk.VBox vbox9;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox9;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox12;

	private global::Gtk.Label label14;

	private global::Gtk.Table table1;

	private global::Gtk.ComboBox combobox3;

	private global::Gtk.ComboBox combobox5;

	private global::Gtk.ComboBox combobox7;

	private global::Gtk.Entry entry11;

	private global::Gtk.Entry entry15;

	private global::Gtk.Entry entry7;

	private global::Gtk.Entry entry9;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label7;

	private global::Gtk.Label label2;

	private global::Gtk.Label label21;

	private global::Gtk.Label label23;

	private global::Gtk.Label label25;

	private global::Gtk.Label label27;

	private global::Gtk.Label label29;

	private global::Gtk.Label label31;

	private global::Gtk.Label label42;

	private global::Gtk.Label label44;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button button13;

	private global::Gtk.Button button15;

	private global::Gtk.Button button1;

	private global::Gtk.Button button4;

	private global::Gtk.Label label11;

	private global::Gtk.VBox vbox13;

	private global::Gtk.Image image1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview5;

	private global::Gtk.Label label13;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label6;

	private global::Gtk.Entry entry3;

	private global::Gtk.Button button3;

	private global::Gtk.Label label4;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.TreeView treeview3;

	private global::Gtk.Label label3;

	private global::Gtk.VBox vbox10;

	private global::Gtk.Label label9;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.TreeView treeview5;

	private global::Gtk.HBox hbox11;

	private global::Gtk.Button button17;

	private global::Gtk.Button button18;

	private global::Gtk.Button button19;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.HomesForSaleAction = new global::Gtk.Action("HomesForSaleAction", global::Mono.Unix.Catalog.GetString("Homes For Sale"), null, null);
		this.HomesForSaleAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Homes For Sale");
		w1.Add(this.HomesForSaleAction, null);
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_File");
		w1.Add(this.FileAction, "function");
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("_Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction, "<Control>o");
		this.CloseAction = new global::Gtk.Action("CloseAction", global::Mono.Unix.Catalog.GetString("C_lose"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Close");
		w1.Add(this.CloseAction, "<Control>l");
		this.NewAction = new global::Gtk.Action("NewAction", global::Mono.Unix.Catalog.GetString("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
		w1.Add(this.NewAction, null);
		this.SaveAction = new global::Gtk.Action("SaveAction", global::Mono.Unix.Catalog.GetString("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action("SaveAsAction", global::Mono.Unix.Catalog.GetString("Save as"), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as");
		w1.Add(this.SaveAsAction, null);
		this.XmlAction = new global::Gtk.Action("XmlAction", global::Mono.Unix.Catalog.GetString("Xml"), null, null);
		this.XmlAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Xml");
		w1.Add(this.XmlAction, null);
		this.ImportFromXMLFileAction = new global::Gtk.Action("ImportFromXMLFileAction", global::Mono.Unix.Catalog.GetString("Import from XML file"), null, null);
		this.ImportFromXMLFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Import from XML file");
		w1.Add(this.ImportFromXMLFileAction, null);
		this.ExportToXMLFileAction = new global::Gtk.Action("ExportToXMLFileAction", global::Mono.Unix.Catalog.GetString("Export to XML file"), null, null);
		this.ExportToXMLFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Export to XML file");
		w1.Add(this.ExportToXMLFileAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Homes For Sale");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menu name='XmlAction' action='XmlAction'><menuitem name='ImportFromXMLFileAction' action='ImportFromXMLFileAction'/><menuitem name='ExportToXMLFileAction' action='ExportToXMLFileAction'/></menu><menuitem name='CloseAction' action='CloseAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox9.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox12 = new global::Gtk.VBox();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Add new/change property");
		this.vbox12.Add(this.label14);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label14]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(11)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.combobox3 = global::Gtk.ComboBox.NewText();
		this.combobox3.Name = "combobox3";
		this.table1.Add(this.combobox3);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.combobox3]));
		w4.TopAttach = ((uint)(4));
		w4.BottomAttach = ((uint)(5));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox5 = global::Gtk.ComboBox.NewText();
		this.combobox5.Name = "combobox5";
		this.table1.Add(this.combobox5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.combobox5]));
		w5.TopAttach = ((uint)(5));
		w5.BottomAttach = ((uint)(6));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox7 = global::Gtk.ComboBox.NewText();
		this.combobox7.Name = "combobox7";
		this.table1.Add(this.combobox7);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.combobox7]));
		w6.TopAttach = ((uint)(6));
		w6.BottomAttach = ((uint)(7));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.entry11.InvisibleChar = '●';
		this.table1.Add(this.entry11);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.entry11]));
		w7.TopAttach = ((uint)(3));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry15 = new global::Gtk.Entry();
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.IsEditable = true;
		this.entry15.InvisibleChar = '●';
		this.table1.Add(this.entry15);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.entry15]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry7 = new global::Gtk.Entry();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.table1.Add(this.entry7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.entry7]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entry9 = new global::Gtk.Entry();
		this.entry9.CanFocus = true;
		this.entry9.Name = "entry9";
		this.entry9.IsEditable = true;
		this.entry9.InvisibleChar = '●';
		this.table1.Add(this.entry9);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.entry9]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.hbox1.Add(this.label7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label7]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.table1.Add(this.hbox1);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
		w12.TopAttach = ((uint)(8));
		w12.BottomAttach = ((uint)(9));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w13.TopAttach = ((uint)(10));
		w13.BottomAttach = ((uint)(11));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Street:");
		this.table1.Add(this.label21);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.label21]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label();
		this.label23.Name = "label23";
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("ZipCode:");
		this.table1.Add(this.label23);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label23]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("City:");
		this.table1.Add(this.label25);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.label25]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label27 = new global::Gtk.Label();
		this.label27.Name = "label27";
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Country:");
		this.table1.Add(this.label27);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.label27]));
		w17.TopAttach = ((uint)(4));
		w17.BottomAttach = ((uint)(5));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label29 = new global::Gtk.Label();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Legal form:");
		this.table1.Add(this.label29);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.label29]));
		w18.TopAttach = ((uint)(5));
		w18.BottomAttach = ((uint)(6));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label31 = new global::Gtk.Label();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Estate Type:");
		this.table1.Add(this.label31);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.label31]));
		w19.TopAttach = ((uint)(6));
		w19.BottomAttach = ((uint)(7));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label42 = new global::Gtk.Label();
		this.label42.Name = "label42";
		this.label42.LabelProp = global::Mono.Unix.Catalog.GetString("label42");
		this.table1.Add(this.label42);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.label42]));
		w20.TopAttach = ((uint)(7));
		w20.BottomAttach = ((uint)(8));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label44 = new global::Gtk.Label();
		this.label44.Name = "label44";
		this.label44.LabelProp = global::Mono.Unix.Catalog.GetString("Estate id:");
		this.table1.Add(this.label44);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.label44]));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox12.Add(this.table1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.table1]));
		w22.Position = 1;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Homogeneous = true;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("Clear fields");
		this.hbox13.Add(this.button13);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button13]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("Add new estate");
		this.hbox13.Add(this.button15);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button15]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Save changes");
		this.hbox13.Add(this.button1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button1]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Cancel change");
		this.hbox13.Add(this.button4);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.button4]));
		w26.PackType = ((global::Gtk.PackType)(1));
		w26.Position = 3;
		w26.Expand = false;
		w26.Fill = false;
		this.vbox12.Add(this.hbox13);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox13]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.notebook1.Add(this.vbox12);
		// Notebook tab
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Add New/change Estate");
		this.notebook1.SetTabLabel(this.vbox12, this.label11);
		this.label11.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox13 = new global::Gtk.VBox();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.vbox13.Add(this.image1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.image1]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView();
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.textview5.Editable = false;
		this.GtkScrolledWindow2.Add(this.textview5);
		this.vbox13.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.GtkScrolledWindow2]));
		w31.Position = 1;
		this.notebook1.Add(this.vbox13);
		global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox13]));
		w32.Position = 1;
		// Notebook tab
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("View Estate");
		this.notebook1.SetTabLabel(this.vbox13, this.label13);
		this.label13.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("City:");
		this.hbox3.Add(this.label6);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label6]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.hbox3.Add(this.entry3);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entry3]));
		w34.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Search");
		this.hbox3.Add(this.button3);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button3]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.vbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.treeview3 = new global::Gtk.TreeView();
		this.treeview3.CanFocus = true;
		this.treeview3.Name = "treeview3";
		this.scrolledwindow2.Add(this.treeview3);
		this.vbox2.Add(this.scrolledwindow2);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow2]));
		w39.Position = 2;
		this.notebook1.Add(this.vbox2);
		global::Gtk.Notebook.NotebookChild w40 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox2]));
		w40.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Search");
		this.notebook1.SetTabLabel(this.vbox2, this.label3);
		this.label3.ShowAll();
		this.hbox9.Add(this.notebook1);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.notebook1]));
		w41.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Available Estates");
		this.vbox10.Add(this.label9);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label9]));
		w42.Position = 0;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.treeview5 = new global::Gtk.TreeView();
		this.treeview5.CanFocus = true;
		this.treeview5.Name = "treeview5";
		this.scrolledwindow1.Add(this.treeview5);
		this.vbox10.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.scrolledwindow1]));
		w44.Position = 1;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("Delete");
		this.hbox11.Add(this.button17);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button17]));
		w45.Position = 0;
		w45.Expand = false;
		w45.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button18 = new global::Gtk.Button();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString("Change");
		this.hbox11.Add(this.button18);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button18]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button19 = new global::Gtk.Button();
		this.button19.CanFocus = true;
		this.button19.Name = "button19";
		this.button19.UseUnderline = true;
		this.button19.Label = global::Mono.Unix.Catalog.GetString("View");
		this.hbox11.Add(this.button19);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button19]));
		w47.Position = 2;
		w47.Expand = false;
		w47.Fill = false;
		this.vbox10.Add(this.hbox11);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox11]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		this.hbox9.Add(this.vbox10);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox10]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		this.vbox9.Add(this.hbox9);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox9]));
		w50.Position = 1;
		this.Add(this.vbox9);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 644;
		this.DefaultHeight = 529;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler(this.OnOpenActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler(this.OnCloseActionActivated);
		this.NewAction.Activated += new global::System.EventHandler(this.OnNewActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler(this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler(this.OnSaveAsActionActivated);
		this.ImportFromXMLFileAction.Activated += new global::System.EventHandler(this.OnImportFromXMLFileActionActivated);
		this.ExportToXMLFileAction.Activated += new global::System.EventHandler(this.OnExportToXMLFileActionActivated);
		this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		this.button15.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.treeview5.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeview5RowActivated);
		this.button17.Clicked += new global::System.EventHandler(this.OnButton17Clicked);
		this.button18.Clicked += new global::System.EventHandler(this.OnButton18Clicked);
		this.button19.Clicked += new global::System.EventHandler(this.OnButton19Clicked);
	}
}
